services:
  - type: web
    name: coopgest
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
