export function getGuideQuestions(id: string): string[] {
  const map: Record<string, string[]> = {
    vision: ["Onde queremos estar daqui a 5 anos?", "O que torna este projeto único?", "Que futuro estamos a construir?"],
    mission: ["Qual é a razão de ser deste projeto?", "Que problema fundamental resolvemos?", "O que nos motiva a fazer este trabalho?"],
    goals: ["O que queremos alcançar concretamente?", "Os objetivos são realistas e mensuráveis?", "Como sabemos que chegámos lá?"],
    objectives: ["Que resultados específicos definimos?", "As metas têm prazo definido?", "Como medimos o progresso?"],
    strategy: ["Qual é a nossa abordagem principal?", "Que alternativas considerámos?", "Porque esta estratégia e não outra?"],
    problem: ["Que problema real estamos a resolver?", "Quem sofre com este problema?", "Que evidências temos da sua existência?"],
    success: ["Como reconhecemos o sucesso?", "Os critérios são acordados por todos?", "O que acontece se não os atingirmos?"],
    impact: ["Que mudança queremos criar?", "Como medimos o impacto a longo prazo?", "Quem beneficia mais com este impacto?"],
    stakeholders: ["Quem são as partes interessadas?", "Como as envolvemos no processo?", "Que expectativas têm?"],
    target_group: ["Quem são os beneficiários diretos?", "Conhecemos bem as suas necessidades?", "Como chegamos até eles?"],
    partners: ["Que organizações colaboram connosco?", "O que cada parceiro contribui?", "Como gerimos as relações de parceria?"],
    community: ["Que comunidade está envolvida?", "Como a envolvemos de forma genuína?", "Que papel tem a comunidade nas decisões?"],
    sponsors: ["Quem financia o projeto?", "Que condições e expectativas têm?", "Como prestamos contas aos financiadores?"],
    decision_makers: ["Quem toma as decisões finais?", "Como é o processo de tomada de decisão?", "Que decisões precisam de aprovação?"],
    team: ["Quem faz parte da equipa?", "Que perfis e competências temos?", "A equipa tem capacidade para o trabalho?"],
    roles: ["Estão os papéis claramente definidos?", "Todos conhecem as suas responsabilidades?", "Há sobreposições ou lacunas?"],
    leadership: ["Como se exerce a liderança?", "As decisões são tomadas de forma transparente?", "Como resolvemos conflitos?"],
    competencies: ["Que competências são essenciais?", "Que lacunas existem na equipa?", "Como desenvolvemos as competências necessárias?"],
    recruitment: ["Como encontramos as pessoas certas?", "Que processo de seleção usamos?", "Como integramos novos membros?"],
    volunteers: ["Qual é o papel dos voluntários?", "Como os recrutamos e apoiamos?", "Como reconhecemos o seu contributo?"],
    scope: ["O que está dentro do âmbito do projeto?", "O que deliberadamente excluímos?", "Como gerimos pedidos fora do âmbito?"],
    activities: ["Que atividades são necessárias?", "Estão ordenadas corretamente?", "Quem é responsável por cada uma?"],
    milestones: ["Quais são os marcos principais?", "São realistas e atingíveis?", "Como celebramos quando os atingimos?"],
    timeline: ["Qual é a duração total do projeto?", "As fases estão bem distribuídas?", "Há folga para imprevistos?"],
    deadlines: ["Que datas são críticas e inegociáveis?", "Estão comunicadas a todos?", "O que acontece se um prazo falhar?"],
    dependencies: ["O que bloqueia o quê?", "Há dependências externas que não controlamos?", "Como gerimos as dependências?"],
    planning: ["Que metodologia de planeamento usamos?", "O plano é realista e partilhado?", "Com que frequência revemos o plano?"],
    budget: ["Qual é o orçamento total disponível?", "Como o distribuímos pelas áreas?", "Como controlamos os gastos?"],
    funding: ["Que fontes de financiamento temos?", "O financiamento cobre todas as necessidades?", "Há alternativas se uma fonte falhar?"],
    resources: ["Que recursos são essenciais?", "Temos acesso a todos os recursos necessários?", "Como gerimos a escassez?"],
    equipment: ["Que equipamento é necessário?", "Compramos, alugamos ou pedimos emprestado?", "Quem é responsável pelo equipamento?"],
    space: ["Onde decorre o trabalho?", "O espaço é adequado às necessidades?", "Há custos de espaço a considerar?"],
    communication: ["Como comunicamos na equipa?", "Que canais e ferramentas usamos?", "Com que frequência comunicamos?"],
    meetings: ["Que tipos de reuniões precisamos?", "Como as tornamos mais eficazes?", "Quem facilita e regista?"],
    reporting: ["A quem reportamos e com que frequência?", "Que formato de relatório usamos?", "Como garantimos que a informação chega a todos?"],
    documentation: ["Que documentos são necessários?", "Onde guardamos a documentação?", "Quem é responsável por mantê-la atualizada?"],
    marketing: ["Como promovemos o projeto?", "Quais são as nossas mensagens principais?", "Que canais de comunicação externa usamos?"],
    social_media: ["Em que plataformas estamos presentes?", "Que tipo de conteúdo partilhamos?", "Quem gere as redes sociais?"],
    risks: ["Que riscos identificámos?", "Quais têm maior probabilidade e impacto?", "Estamos todos cientes dos riscos?"],
    mitigation: ["Como mitigamos cada risco?", "Há planos de contingência?", "Quem é responsável por cada risco?"],
    quality: ["Que padrões de qualidade seguimos?", "Como verificamos a qualidade do trabalho?", "Quem aprova os entregáveis?"],
    compliance: ["Que requisitos legais temos?", "Estamos em conformidade com as normas aplicáveis?", "Quem verifica a conformidade?"],
    security: ["Que dados sensíveis gerimos?", "Como protegemos a privacidade?", "Que medidas de segurança temos?"],
    monitoring: ["Como acompanhamos o progresso?", "Com que frequência fazemos revisões?", "O que fazemos quando algo desvia?"],
    kpis: ["Que indicadores usamos?", "Os KPIs estão alinhados com os objetivos?", "Como recolhemos os dados dos indicadores?"],
    evaluation: ["Como avaliamos os resultados?", "Quem faz a avaliação?", "Como usamos os resultados da avaliação?"],
    feedback: ["Como recolhemos feedback?", "De quem precisamos de feedback?", "Como incorporamos o feedback no projeto?"],
    lessons: ["Que lições aprendemos até agora?", "Como partilhamos o conhecimento?", "O que faríamos de forma diferente?"],
    data: ["Que dados recolhemos?", "Como garantimos a qualidade dos dados?", "Como usamos dados para tomar decisões?"],
    deliverables: ["Quais são os entregáveis concretos?", "Estão claramente definidos?", "Quem aprova cada entregável?"],
    launch: ["Como lançamos os resultados?", "Que eventos ou ações marcam a entrega?", "Como comunicamos o lançamento?"],
    sustainability: ["Como garantimos a continuidade?", "Que recursos são necessários a longo prazo?", "Quem assume responsabilidade após o projeto?"],
    scaling: ["O projeto pode crescer?", "Que condições são necessárias para escalar?", "Queremos replicar noutros contextos?"],
    exit: ["Como termina o projeto de forma responsável?", "Que processos de encerramento temos?", "Como entregamos o trabalho a outros?"],
    legacy: ["O que fica depois do projeto?", "Que conhecimento ou estruturas perduam?", "Como garantimos que o legado é positivo?"],
    change: ["Como gerimos mudanças no âmbito?", "Que processo seguimos para aprovar mudanças?", "Como comunicamos mudanças à equipa?"],
  };
  return map[id] ?? ["Como abordamos este aspeto?", "Que prioridade tem no projeto?", "Quem é responsável por este tema?"];
}
